spring: 
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
  application:
    name: microservicecloud-config-xinyue-dev

---

spring:
  profiles: test
  application:
    name: microservicecloud-config-xinyue-test